Algoritmo "Atividade 1"
Var
// --- Variáveis da questão 1 ---
Excesso, resultado , P, M : real


Inicio
// ------- QUESTÃO 1 -------
escreval("Qual é o peso peixe: ")
leia(P)
excesso <- 50

se (P > excesso) entao

resultado <- P - excesso

 M <- 4*resultado
  escreval("Você têm",P, "Kg de peixe!")
  escreval("A multa a pagar é ", m , "R$")
   senao
escreval("Sem multa a pagar, porque você não atingiu o limite!")
fimse
Fimalgoritmo
