Algoritmo "aula4pt2"
Var
senha,usuario, usuarioCadastrado, senhaCadastrada : caractere
Inicio

escreval("Qual é o Usuario")
leia(usuario)
escreval("Qual é a senha:")
leia(senha)

usuarioCadastrado <- "Kaua"
senhaCadastrada <- "123"

se (senha = senhaCadastrada e (usuario = usuarioCadastrado)) entao
escreval("Usuario correto!")

senao

escreval("Usuario errado!")
fimse

// se (s <> sc) entao
// senha incorreta
// senao (u <> uc) entao
// senao
// Seja bem vindo
Fimalgoritmo